# Generated by Django 4.1.3 on 2023-02-20 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leadslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('office', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, default=datetime.datetime(2023, 2, 20, 20, 52, 30, 503914))),
                ('start_date', models.DateTimeField(null=True)),
                ('salary', models.IntegerField(null=True)),
            ],
        ),
    ]
